name: Tag and Release
author: fdiesel
inputs:
  token:
    description: The github token. Use secrets.GITHUB_TOKEN
    required: true
  path:
    description: Path to package.json file
    default: "./package.json"
    required: false
  prefix:
    description: Optional version prefix
    default: ""
    required: false
outputs:
  created:
    description: If tag and release was created
  version:
    description: Version in package.json
runs:
  using: node16
  main: dist/index.js
