name: Node Release
description: Creates a release based on the package.json version
branding:
  icon: tag
  color: blue
author: fdiesel
inputs:
  token:
    description: The github token. Use secrets.GITHUB_TOKEN
    required: true
  path:
    description: Path to package.json file
    default: './package.json'
    required: false
  prefix:
    description: Optional version prefix
    default: ''
    required: false
  notes:
    description: Optional generating release notes
    default: 'true'
    required: false
  dry_run:
    description: Optional dry run
    default: 'false'
    required: false
outputs:
  created:
    description: If tag and release was created
  version:
    description: Version in package.json
  changelog:
    description: List of all commits since last release
  version_changed:
    description: If version has changed
runs:
  using: node20
  main: index.js
