name: Release

on:
  push:
    branches: dist

jobs:

  release:

    runs-on: ubuntu-latest
    needs: test

    outputs:
      created: ${{ steps.release.outputs.created }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release
        id: release
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: v
